name: "Step 1: Prep Release"
on:
  workflow_dispatch:
    inputs:
      version_spec:
        description: "New Version Specifier"
        default: "next"
        required: false
      branch:
        description: "The branch to target"
        required: false
      post_version_spec:
        description: "Post Version Specifier"
        required: false
      since:
        description: "Use PRs with activity since this date or git reference"
        required: false
      since_last_stable:
        description: "Use PRs with activity since the last stable git tag"
        required: false
        type: boolean
jobs:
  prep_release:
    runs-on: ubuntu-latest
    steps:
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: install-releaser
        run: pip install -q git+https://github.com/jupyter-server/jupyter_releaser.git@v2

      - id: prep-release
        shell: bash -eux {0}
        run: |
          export GITHUB_ACCESS_TOKEN=${{ secrets.ADMIN_GITHUB_TOKEN }}
          export GITHUB_ACTOR=alanhamlett
          if [ ! -z ${{ github.event.inputs.branch }} ]; then
            export RH_BRANCH=${{ github.event.inputs.branch }}
          fi
          export RH_VERSION_SPEC=${{ github.event.inputs.version_spec }}
          export RH_POST_VERSION_SPEC=${{ github.event.inputs.post_version_spec }}
          export RH_SINCE=${{ github.event.inputs.since }}
          export RH_SINCE_LAST_STABLE=${{ github.event.inputs.since_last_stable }}

          python -m jupyter_releaser.actions.prep_release

      - run: |
          echo "## Next Step" >> $GITHUB_STEP_SUMMARY
          echo "(Optional): Review Draft Release: ${{ steps.prep-release.outputs.release_url }}" >> $GITHUB_STEP_SUMMARY
          echo "Run Step 2: Publish Release workflow"
